# language: php
build:
    environment:
        php: 8.1
    tests:
        override:
            - phpcs-run --standard=phpcs.xml.dist
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
  excluded_paths:
    - "MO4/Tests/*/*.inc"
    - "integrationtests/*"
  dependency_paths:
    - "vendor/"
checks:
    php: true
