sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer install
  - mkdir -p vendor/squizlabs/php_codesniffer/src/Standards/MO4
  - cp ruleset.xml vendor/squizlabs/php_codesniffer/src/Standards/MO4/
  - cp -R Sniffs vendor/squizlabs/php_codesniffer/src/Standards/MO4/
  - cp -R Tests vendor/squizlabs/php_codesniffer/src/Standards/MO4/
  - (cd vendor/squizlabs/php_codesniffer/CodeSniffer/Standards ; git clone https://github.com/djoos/Symfony-coding-standard.git Symfony ; mv Symfony/Symfony/* Symfony/)

script:
  - (cd vendor/squizlabs/php_codesniffer ; ../../bin/phpunit --filter MO4)
  - (mkdir -p vendor/squizlabs/php_codesniffer/src/Standards/PHPCS ; cp vendor/squizlabs/php_codesniffer/phpcs.xml.dist vendor/squizlabs/php_codesniffer/src/Standards/PHPCS/ruleset.xml)
  - ./vendor/squizlabs/php_codesniffer/bin/phpcs ./vendor/squizlabs/php_codesniffer/src/Standards/MO4/Sniffs --standard=PHPCS --report=summary -np
