sudo: false
language: php
php:
  - 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
  - |
    vendor/bin/phpstan analyse --level=max --no-progress -c .phpstan.neon MO4 tests
    pecl install -f ast-0.1.6
    composer require phan/phan --dev
    vendor/bin/phan -i
  - php -d zend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: HcN5Gm6bfN8x5AP7BAw3QxKvyH9tEMd9ZnzlsGGitjCxvfLf86RIEoBkbLgBFm7Kzzue4V9WWlcop301vF7TFcDyCDQuQop/VQaY0iBUpauCLcu9M0G2LdbFvc1IXihFZGReFMm7rvjGPX8+V6vcEdJHG/fq+Fyf/xgKDTFO4KQ=
