sudo: false
os:
  - linux
language: php
php:
  - 7.1
  - 7.2
  - 7.3
env:
  - DEPENDENCIES=lowest
  - DEPENDENCIES=highest

addons:
  apt:
    packages:
      - libxml2-utils # for xmllint

cache:
  directories:
  - $HOME/.composer/cache

before_script:
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then pecl install -f ast-1.0.7; fi; # Install AST extension, as phan requires it
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer require phan/phan --dev; fi; # Install phan, now that we have the AST extension

script:
  - xmllint --noout --schema vendor/squizlabs/php_codesniffer/phpcs.xsd MO4/ruleset.xml # validate MO4's ruleset XML
  - vendor/bin/phpcs --standard=MO4 integrationtests/testfile.php # Check, if all the sniffs work with the current dependencies
  - vendor/bin/phpunit # Run tests
  - vendor/bin/phpcs # Stylecheck against PHPCS's ruleset
  - vendor/bin/phpstan analyse --level=max --no-progress -c .phpstan.neon MO4 tests # Run PHPStan
  - if [ "${DEPENDENCIES}" = "highest" ]; then vendor/bin/phan -i; fi; # Run phan
  # Generate Code coverage report
  - |
    if [ "${TRAVIS_PHP_VERSION}" == "7.3" ] && [ "${DEPENDENCIES}" = "highest" ]; then
      echo 'xdebug.mode = "coverage"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      php -d zend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml
    fi

jobs:
  include:
    - stage: Test
      name: PHP:7.3 Windows
      os: windows
      cache:
        directories:
          - C:/Users/travis/AppData/Local/Composer
      language: sh # No PHP currently
      env:
        - PHP_VERSION=7.3
        - DEPENDENCIES=lowest
      install:
        - choco install php --version=7.3 --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH
      script:
        - git config core.autocrlf false # fix CRLF issues
        - git add --renormalize .
        - git reset --hard
        - vendor/bin/phpcs --standard=MO4 integrationtests/testfile.php # Check, if all the sniffs work with the current dependencies
        - vendor/bin/phpunit # Run tests
        - vendor/bin/phpcs # Stylecheck against PHPCS's ruleset
        - vendor/bin/phpstan analyse --level=max --no-progress -c .phpstan.neon MO4 tests # Run PHPStan

after_success:
- curl -s https://codecov.io/bash | bash

notifications:
  slack:
    secure: HcN5Gm6bfN8x5AP7BAw3QxKvyH9tEMd9ZnzlsGGitjCxvfLf86RIEoBkbLgBFm7Kzzue4V9WWlcop301vF7TFcDyCDQuQop/VQaY0iBUpauCLcu9M0G2LdbFvc1IXihFZGReFMm7rvjGPX8+V6vcEdJHG/fq+Fyf/xgKDTFO4KQ=
