sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
  - |
    if [ `php -r "echo (int) version_compare(PHP_VERSION, '7.0', '>=');"` = "1" ]; then
      composer require phpstan/phpstan --dev
      vendor/bin/phpstan analyse --level=max --no-progress -c .phpstan.neon MO4 tests
    fi
  - php -d zend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
