sudo: false
language: php
matrix:
  include:
  - php: 5.6
    env: DEPENDENCIES=lowest
  - php: 5.6
    env: DEPENDENCIES=highest
  - php: 7.0
    env: DEPENDENCIES=lowest
  - php: 7.0
    env: DEPENDENCIES=highest
  - php: 7.1
    env: DEPENDENCIES=lowest
  - php: 7.1
    env: DEPENDENCIES=highest
  - php: 7.2
    env: DEPENDENCIES=lowest
  - php: 7.2
    env: DEPENDENCIES=highest

cache:
  directories:
  - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;

script:
  - vendor/bin/phpcs --standard=MO4 integrationtests/testfile.php
  - vendor/bin/phpunit
  - vendor/bin/phpcs
  - |
    if [ `php -r "echo (int) version_compare(PHP_VERSION, '7.0', '>=');"` = "1" ]; then
      composer require phpstan/phpstan --dev
      composer require phpstan/phpstan-strict-rules --dev
      vendor/bin/phpstan analyse --level=max --no-progress -c .phpstan.neon MO4 tests
      pecl install -f ast-0.1.6
      composer require phan/phan --dev
      vendor/bin/phan -i
    fi
  - php -d zend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: HcN5Gm6bfN8x5AP7BAw3QxKvyH9tEMd9ZnzlsGGitjCxvfLf86RIEoBkbLgBFm7Kzzue4V9WWlcop301vF7TFcDyCDQuQop/VQaY0iBUpauCLcu9M0G2LdbFvc1IXihFZGReFMm7rvjGPX8+V6vcEdJHG/fq+Fyf/xgKDTFO4KQ=
