<?php

$fail = [
    1];

$values  = [
    'Test:1' => [
        'object_id'         => 1,
        'object_class'      => 'Test',
        'object_class_name' => 'TestClass',
        'object_name'       => 'TestObject',
        'id'                => 'Test:1',],
    'Test:2' => [
        'object_id'         => 2,
        'object_class'      => 'Test',
        'object_class_name' => 'TestClass',
        'object_name'       => 'TestObject',
        'id'                => 'Test:2',],];


$fail = array(
    1);

$fail = array(1,
    2,
);

$fail = [     1,
2,
];

$fail = array( // fail
);
